@startuml

title __DTO's Class Diagram__\n

  namespace ru.ifmo.se.iap.schoolOfPeopleX {
    namespace model {
      namespace dto {
        class ru.ifmo.se.iap.schoolOfPeopleX.model.dto.AbstractLessonDTO {
            - dayOfWeek : DayOfWeek
            - lessonEnd : OffsetTime
            - lessonStart : OffsetTime
            + AbstractLessonDTO()
            + AbstractLessonDTO()
            + equals()
            + getDayOfWeek()
            + getLessonEnd()
            + getLessonStart()
            + hashCode()
            + setDayOfWeek()
            + setLessonEnd()
            + setLessonStart()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace ru.ifmo.se.iap.schoolOfPeopleX {
    namespace model {
      namespace dto {
        class ru.ifmo.se.iap.schoolOfPeopleX.model.dto.AccountDTO {
            - birthday : ZonedDateTime
            - email : String
            - firstName : String
            - heroName : String
            - lastName : String
            - password : String
            - passwordConfirm : String
            + AccountDTO()
            + AccountDTO()
            + equals()
            + getBirthday()
            + getEmail()
            + getFirstName()
            + getHeroName()
            + getLastName()
            + getPassword()
            + getPasswordConfirm()
            + hashCode()
            + setBirthday()
            + setEmail()
            + setFirstName()
            + setHeroName()
            + setLastName()
            + setPassword()
            + setPasswordConfirm()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace ru.ifmo.se.iap.schoolOfPeopleX {
    namespace model {
      namespace dto {
        class ru.ifmo.se.iap.schoolOfPeopleX.model.dto.AccountRatingDTO {
            - firstName : String
            - heroName : String
            - lastName : String
            - rating : Double
            + AccountRatingDTO()
            + AccountRatingDTO()
            + equals()
            + getFirstName()
            + getHeroName()
            + getLastName()
            + getRating()
            + hashCode()
            + setFirstName()
            + setHeroName()
            + setLastName()
            + setRating()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace ru.ifmo.se.iap.schoolOfPeopleX {
    namespace model {
      namespace dto {
        class ru.ifmo.se.iap.schoolOfPeopleX.model.dto.CourseDTO {
            - abilityId : Long
            - abstractLessons : Set<AbstractLessonDTO>
            - courseEnd : LocalDate
            - courseStart : LocalDate
            - description : String
            - lessonsForPassed : Long
            - maximumStudents : Long
            - title : String
            + CourseDTO()
            + CourseDTO()
            + equals()
            + getAbilityId()
            + getAbstractLessons()
            + getCourseEnd()
            + getCourseStart()
            + getDescription()
            + getLessonsForPassed()
            + getMaximumStudents()
            + getTitle()
            + hashCode()
            + setAbilityId()
            + setAbstractLessons()
            + setCourseEnd()
            + setCourseStart()
            + setDescription()
            + setLessonsForPassed()
            + setMaximumStudents()
            + setTitle()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace ru.ifmo.se.iap.schoolOfPeopleX {
    namespace model {
      namespace dto {
        class ru.ifmo.se.iap.schoolOfPeopleX.model.dto.PasswordRecoveryDTO {
            - email : String
            + PasswordRecoveryDTO()
            + PasswordRecoveryDTO()
            + equals()
            + getEmail()
            + hashCode()
            + setEmail()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace ru.ifmo.se.iap.schoolOfPeopleX {
    namespace model {
      namespace dto {
        class ru.ifmo.se.iap.schoolOfPeopleX.model.dto.RatingDTO {
            - lessonId : Long
            - rating : Long
            - studentId : Long
            + RatingDTO()
            + RatingDTO()
            + equals()
            + getLessonId()
            + getRating()
            + getStudentId()
            + hashCode()
            + setLessonId()
            + setRating()
            + setStudentId()
            + toString()
            # canEqual()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
